// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $$0 from "./islands/AddToCartAvatar.tsx";
import * as $$1 from "./islands/AddToCartButton.tsx";
import * as $$2 from "./islands/BawFilters.tsx";
import * as $$3 from "./islands/BreadcrumbControls.tsx";
import * as $$4 from "./islands/HeaderButton.tsx";
import * as $$5 from "./islands/HeaderModals.tsx";
import * as $$6 from "./islands/HeaderSearchbar.tsx";
import * as $$7 from "./islands/Newsletter.tsx";
import * as $$8 from "./islands/OutOfStock.tsx";
import * as $$9 from "./islands/ProductCardSimilar.tsx";
import * as $$10 from "./islands/ProductGallery.tsx";
import * as $$11 from "./islands/ProductImageZoom.tsx";
import * as $$12 from "./islands/ProductReviews.tsx";
import * as $$13 from "./islands/ReadMore.tsx";
import * as $$14 from "./islands/SearchControls.tsx";
import * as $$15 from "./islands/ShareButton.tsx";
import * as $$16 from "./islands/ShippingSimulation.tsx";
import * as $$17 from "./islands/Sidebar.tsx";
import * as $$18 from "./islands/SizebayButtons.tsx";
import * as $$19 from "./islands/SizebayIframe.tsx";
import * as $$20 from "./islands/SliderJS.tsx";
import * as $$21 from "./islands/WishlistButton.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
  },
  islands: {
    "./islands/AddToCartAvatar.tsx": $$0,
    "./islands/AddToCartButton.tsx": $$1,
    "./islands/BawFilters.tsx": $$2,
    "./islands/BreadcrumbControls.tsx": $$3,
    "./islands/HeaderButton.tsx": $$4,
    "./islands/HeaderModals.tsx": $$5,
    "./islands/HeaderSearchbar.tsx": $$6,
    "./islands/Newsletter.tsx": $$7,
    "./islands/OutOfStock.tsx": $$8,
    "./islands/ProductCardSimilar.tsx": $$9,
    "./islands/ProductGallery.tsx": $$10,
    "./islands/ProductImageZoom.tsx": $$11,
    "./islands/ProductReviews.tsx": $$12,
    "./islands/ReadMore.tsx": $$13,
    "./islands/SearchControls.tsx": $$14,
    "./islands/ShareButton.tsx": $$15,
    "./islands/ShippingSimulation.tsx": $$16,
    "./islands/Sidebar.tsx": $$17,
    "./islands/SizebayButtons.tsx": $$18,
    "./islands/SizebayIframe.tsx": $$19,
    "./islands/SliderJS.tsx": $$20,
    "./islands/WishlistButton.tsx": $$21,
  },
  baseUrl: import.meta.url,
};

export default manifest;
