// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$0 from "./loaders/productDetailsPageWithReviews.ts";
import * as $$$1 from "./loaders/reviewsandratings.ts";
import * as $$$$$$0 from "./sections/WishlistGallery.tsx";
import * as $$$$$$1 from "./sections/LinkTree.tsx";
import * as $$$$$$2 from "./sections/BannerPLPCampaign.tsx";
import * as $$$$$$3 from "./sections/Features.tsx";
import * as $$$$$$4 from "./sections/BannerPLP.tsx";
import * as $$$$$$5 from "./sections/AuthIframe.tsx";
import * as $$$$$$6 from "./sections/ReadMore.tsx";
import * as $$$$$$7 from "./sections/BannerGrid.tsx";
import * as $$$$$$8 from "./sections/BawHighlights.tsx";
import * as $$$$$$9 from "./sections/SearchResult.tsx";
import * as $$$$$$10 from "./sections/BannerMovieImg.tsx";
import * as $$$$$$11 from "./sections/BannerFourCards.tsx";
import * as $$$$$$12 from "./sections/ProductShelf.tsx";
import * as $$$$$$13 from "./sections/BawBanner.tsx";
import * as $$$$$$14 from "./sections/Footer.tsx";
import * as $$$$$$15 from "./sections/SearchBreadControls.tsx";
import * as $$$$$$16 from "./sections/SEOPLPBaw.tsx";
import * as $$$$$$17 from "./sections/CookieConsent.tsx";
import * as $$$$$$18 from "./sections/DesignSystem.tsx";
import * as $$$$$$19 from "./sections/BannerCardPosition.tsx";
import * as $$$$$$20 from "./sections/SEOPDPBaw.tsx";
import * as $$$$$$21 from "./sections/Header.tsx";
import * as $$$$$$22 from "./sections/BawFeatures.tsx";
import * as $$$$$$23 from "./sections/ProductDetails.tsx";
import * as $$$$$$24 from "./sections/BannerFull.tsx";
import * as $$$$$$25 from "./sections/HeadBanner.tsx";
import * as $$$$$$26 from "./sections/Highlights.tsx";
import * as $$$$$$27 from "./sections/WhatsApp.tsx";
import * as $$$$$$28 from "./sections/BawProductShelf.tsx";
import * as $$$$$$29 from "./sections/Carousel.tsx";
import * as $$$$$$$$$0 from "./actions/createReview.ts";
import * as $$$$$$$$$$$0 from "./apps/site.ts";

const manifest = {
  "loaders": {
    "deco-sites/bawclothing/loaders/productDetailsPageWithReviews.ts": $$$0,
    "deco-sites/bawclothing/loaders/reviewsandratings.ts": $$$1,
  },
  "sections": {
    "deco-sites/bawclothing/sections/AuthIframe.tsx": $$$$$$5,
    "deco-sites/bawclothing/sections/BannerCardPosition.tsx": $$$$$$19,
    "deco-sites/bawclothing/sections/BannerFourCards.tsx": $$$$$$11,
    "deco-sites/bawclothing/sections/BannerFull.tsx": $$$$$$24,
    "deco-sites/bawclothing/sections/BannerGrid.tsx": $$$$$$7,
    "deco-sites/bawclothing/sections/BannerMovieImg.tsx": $$$$$$10,
    "deco-sites/bawclothing/sections/BannerPLP.tsx": $$$$$$4,
    "deco-sites/bawclothing/sections/BannerPLPCampaign.tsx": $$$$$$2,
    "deco-sites/bawclothing/sections/BawBanner.tsx": $$$$$$13,
    "deco-sites/bawclothing/sections/BawFeatures.tsx": $$$$$$22,
    "deco-sites/bawclothing/sections/BawHighlights.tsx": $$$$$$8,
    "deco-sites/bawclothing/sections/BawProductShelf.tsx": $$$$$$28,
    "deco-sites/bawclothing/sections/Carousel.tsx": $$$$$$29,
    "deco-sites/bawclothing/sections/CookieConsent.tsx": $$$$$$17,
    "deco-sites/bawclothing/sections/DesignSystem.tsx": $$$$$$18,
    "deco-sites/bawclothing/sections/Features.tsx": $$$$$$3,
    "deco-sites/bawclothing/sections/Footer.tsx": $$$$$$14,
    "deco-sites/bawclothing/sections/HeadBanner.tsx": $$$$$$25,
    "deco-sites/bawclothing/sections/Header.tsx": $$$$$$21,
    "deco-sites/bawclothing/sections/Highlights.tsx": $$$$$$26,
    "deco-sites/bawclothing/sections/LinkTree.tsx": $$$$$$1,
    "deco-sites/bawclothing/sections/ProductDetails.tsx": $$$$$$23,
    "deco-sites/bawclothing/sections/ProductShelf.tsx": $$$$$$12,
    "deco-sites/bawclothing/sections/ReadMore.tsx": $$$$$$6,
    "deco-sites/bawclothing/sections/SearchBreadControls.tsx": $$$$$$15,
    "deco-sites/bawclothing/sections/SearchResult.tsx": $$$$$$9,
    "deco-sites/bawclothing/sections/SEOPDPBaw.tsx": $$$$$$20,
    "deco-sites/bawclothing/sections/SEOPLPBaw.tsx": $$$$$$16,
    "deco-sites/bawclothing/sections/WhatsApp.tsx": $$$$$$27,
    "deco-sites/bawclothing/sections/WishlistGallery.tsx": $$$$$$0,
  },
  "actions": {
    "deco-sites/bawclothing/actions/createReview.ts": $$$$$$$$$0,
  },
  "apps": {
    "deco-sites/bawclothing/apps/site.ts": $$$$$$$$$$$0,
  },
  "name": "deco-sites/bawclothing",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
